/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.MateriaHorario;

import Controlador.Materia.ControladorCrudMateria;
import Controlador.MateriaHorario.ControladorCrudMateriaHorario;
import Entidades.Horario;
import Entidades.HorarioMateria;
import Entidades.Materia;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megan
 */
public class JInternalFrameNuevaMateriaHorario extends javax.swing.JInternalFrame {

    Materia materiaConsulta=new Materia();
    Horario horarioCrear = new Horario();
    
    HorarioMateria horarioMateria = new HorarioMateria();
    List<Horario> lstHorarios;
    
    ControladorCrudMateria controladorMateria = new ControladorCrudMateria();
    ControladorCrudMateriaHorario controladorHorarioMateria = new ControladorCrudMateriaHorario();
    
    DefaultTableModel modelo;
    Object []horario = new Object[4];
  
    //Constructor
    public JInternalFrameNuevaMateriaHorario() {
        initComponents();
        habilitarDeshabilitar(false);
        crearTabla();
        btnGuardar.setEnabled(false);
    }
    
    public void crearTabla(){
        try{
            modelo = new DefaultTableModel();
            dgHorarios.setModel(modelo);
            modelo.addColumn("Id");
            modelo.addColumn("Día");
            modelo.addColumn("Hora de Inicio");
            modelo.addColumn("Hora de Finalización");  
            ocultarColumnas();
        }catch(Exception e){
            System.out.println("No se puede crear tabla");
        }   
    }
    
    public void ocultarColumnas(){
        dgHorarios.getColumnModel().getColumn(0).setMaxWidth(0);
        dgHorarios.getColumnModel().getColumn(0).setMinWidth(0);
        dgHorarios.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    //Mètodo para habilitar y deshabilitar cuadros de textos
    public void habilitarDeshabilitar (boolean estado)
    {
        txtMateria.setEnabled(estado);
        txtHorario.setEnabled(estado);
    }
    
    //Método para llenar los campos de la interfaz con los datos obtenidos de la busqueda
    public void setDatosMateriaConsulta(){
        if(materiaConsulta.getMateria()!=null){
            txtMateria.setText(materiaConsulta.getMateria());
            crearTabla();
            for(Horario h:lstHorarios){
                horario[0]=h.getIdhorario();
                horario[1]=h.getDia();
                horario[2]=h.getHoraInicio();
                horario[3]=h.getHoraFin();
                modelo.addRow(horario);
            }
        }else{
            txtMateria.setText("");
        }
    }
    
    //Metodo de objecto horarioMateria a crear/// Estado: si=1, no=0
    public void setDatosHorarioMateria(){
        horarioMateria.setIdhorario(horarioCrear);
        horarioMateria.setIdmateria(materiaConsulta);
        horarioMateria.setEstado(1);
    }
    
     public boolean validarDatos(){
        boolean bandera; 
        if(!txtMateria.getText().equals("") && !txtHorario.getText().equals("")){
            bandera=true;
        }else{
            bandera=false;
        }
        return bandera;
    }
     
    public boolean consultarHorarioUnico(){
        boolean bandera;
        HorarioMateria hm = new HorarioMateria();
        hm=controladorHorarioMateria.consultarHorarioMateria(materiaConsulta, horarioCrear);
        if(hm.getIdmateriahorario()==null){
            bandera=true;
            System.out.println(hm.getIdmateria()+" "+hm.getIdhorario());
        }else{
            bandera=false;
            System.out.println(hm.getIdmateria()+" "+hm.getIdhorario());
        }
        
        return bandera;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblImagPeq = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtParamBusqMateria = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgHorarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setPreferredSize(new java.awt.Dimension(1168, 647));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1168, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Materia-Horario"));

        jLabel1.setText("Materia Escogida:");

        lblFechaInicio.setText("Horario Escogido:");

        txtMateria.setName(""); // NOI18N
        txtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriaActionPerformed(evt);
            }
        });

        txtHorario.setName(""); // NOI18N

        btnGuardar.setLabel("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechaInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnGuardar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lblImagPeq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logopeq.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetro de Búsqueda"));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el nombre de la Materia:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtParamBusqMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtParamBusqMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(56, 56, 56))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Horarios"));

        dgHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgHorariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgHorarios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblImagPeq)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagPeq))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Mètodo consultar 
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
            materiaConsulta.setMateria(txtParamBusqMateria.getText().toUpperCase());
            materiaConsulta = controladorMateria.consultarMateriaPorNombre(txtParamBusqMateria.getText().toUpperCase());
            lstHorarios = controladorHorarioMateria.consultarListaHorarios();          
            System.out.println(txtParamBusqMateria.getText());
                  
            if(materiaConsulta!=null){  
                if(!lstHorarios.isEmpty()){
                    setDatosMateriaConsulta();
                }else{
                    JOptionPane.showMessageDialog(null, "No se encuentra registrados horarios");
                }
            }
            txtParamBusqMateria.setText("");
            habilitarDeshabilitar(false);
            btnGuardar.setEnabled(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se encuentra registrada");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        setDatosHorarioMateria();
        ControladorCrudMateriaHorario controlador = new ControladorCrudMateriaHorario();
        try {
            if(validarDatos()){
                if(consultarHorarioUnico()){
                    controlador.crearHorarioMateria(horarioMateria);
                    JOptionPane.showMessageDialog(null,"Horario Asignado");
                }else{
                    JOptionPane.showMessageDialog(null,"El horario ya se encuentra registrado");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un horario");
            }
        } catch (Exception e) {
            Logger.getLogger(JInternalFrameNuevaMateriaHorario.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null,"Seleccione un horario");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMateriaActionPerformed

    private void dgHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgHorariosMouseClicked
        int fila = dgHorarios.rowAtPoint(evt.getPoint());
        horarioCrear.setIdhorario(Integer.parseInt(dgHorarios.getValueAt(fila, 0).toString()));
        txtHorario.setText(dgHorarios.getValueAt(fila, 1).toString()+ ": "+dgHorarios.getValueAt(fila, 2).toString()
                            + " - "+dgHorarios.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_dgHorariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTable dgHorarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblImagPeq;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtParamBusqMateria;
    // End of variables declaration//GEN-END:variables
}
