/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Calificacion.itemNuevoEPanel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.xml.bind.annotation.XmlElement;

/**
 *
 * @author nathy
 */
public class JGenericInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form JGenericInternalFrame
     */
    public JGenericInternalFrame(String nombrePanel) {
        initComponents();
        jScrollPane1=new JScrollPane();
        JPanel panel;
        System.out.println("nombre: "+nombrePanel);
        switch(nombrePanel){
            case "itemNuevoE":
                panel=new itemNuevoEPanel();
                System.out.println("entro");
                break;
            default: 
                panel=new JPanel();
        
        }
        jScrollPane1.add(panel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
